config/routes.rb
Rails.application.routes.draw do
  get '/page-2', to: 'page2#index', as: 'page2'
  root 'home#index'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resources :agents

  
  namespace :api do
    namespace :v1 do

      resources :users, only: [:show] do
        collection do
          post :signin
        end
      end

      resources :profile

    end
  end
  
end

app/models/address.rb
class Address < ApplicationRecord
  enum status: { current: 1, permanent: 2 }
  acts_as_favoritable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/educational_background.rb
class EducationalBackground < ApplicationRecord
  ## Associations
  belongs_to :user
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/job_reference.rb
class JobReference < ApplicationRecord
  ## Associations
  belongs_to :user
end

app/models/personal_info.rb
class PersonalInfo < ApplicationRecord
  enum gender: {male: 1, female: 2 }
  acts_as_favoritor
  
  ## Associations
  belongs_to :user

  def update_addresses addresses    
    if addresses.any?
      addresses.each do |address|
        add = Address.where(id: address[:id]).first_or_initialize
        add.update_attributes!(
          city:         address[:city], 
          state:        address[:state], 
          postal_code:  address[:postal_code], 
          country:      address[:country], 
          status:       address[:status])

        self.favorite(add)
      end
    end    
  end


end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  paginates_per 10

  ## Associations
  has_one :personal_info
  has_one :educational_background
  
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Validations
  validates :email, presence: true
  validates :password, presence: true, on: :create

  ## Hooks  

         
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!, :authorize_admin
  before_action :set_user, only: [:edit, :update]

  def index
    @users = User.all    
  end

  def new
    @user = User.new
  end

  def edit    
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_index_path, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def create
    @user = User.new(user_params)
    
    respond_to do |format|
      if @user.save        
        UserMailer.new_user_account(@user, user_params[:password]).deliver_now
        format.html { redirect_to admin_index_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    def user_params
      if params[:user][:password].blank?
        params.fetch(:user, {}).permit(:name, :email)
      else
        params.fetch(:user, {}).permit(:name, :email, :password)
      end
    end

    def set_user
      @user = User.friendly.find(params[:id])
    end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:edit, :update]

  def index
    @agents = User.with_role(:agent).page(params[:page])
  end

  def new
    @agent = User.new
    @path = "/agents"
  end

  def edit
    @path = "/agents/#{@agent.id}"
  end

  def create
    @user = User.new(user_params)
    
    respond_to do |format|
      if @user.save
        ## Assign role to agent
        @user.add_role :agent

        ## Send email to agent
        AgentMailer.new_account(@user, user_params[:password]).deliver_now
        format.html { redirect_to agents_path, notice: 'Agent has been added successfully.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      begin
        @agent.update!(user_params)
        format.html { redirect_to agents_path, notice: 'Agent was successfully updated.' }
      rescue Exception => e
        @path = "/agents/#{@agent.id}"
        format.html { render :edit }
      end      
    end
  end

  private
    def user_params      
      if params[:user][:password].blank?        
        params.fetch(:user, {}).permit(:name, :email)
      else
        params.fetch(:user, {}).permit(:name, :email, :password)
      end
    end

    def set_user
      @agent = User.find(params[:id])
    end

end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ApplicationController
  before_action :authenticate_via_token
  skip_before_action :verify_authenticity_token

  private
    def authenticate_via_token
      if request.headers[:Authorization].blank?
        return render json: { success: false, msg: 'Authentication token not found.' }, status: 401
      end
      
      @token = request.headers[:Authorization]

      begin
        @user = User.find_by(jwt_token: @token)
        @decoded_token = JWT.decode @token, Settings.hmac_secret, true, { algorithm: 'HS256' }

        if !@user && !@user.try(:id).try(:eql?, @decoded_token.first["data"]["user"]["id"])
          return render json: {success: false, msg: 'Invalid token.'}, status: 401  
        end
                
      rescue JWT::ExpiredSignature
        return render json: {success: false, msg: 'Token has expired.'}, status: 401
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Default layout
  layout 'main/layout-2'

  private
    def authorize_admin
      if user_signed_in? && !current_user.has_role?(:admin)
        redirect_to root_path, notice: 'You are not authorized to access this page.'
      end
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @title = 'Dashboard'
  end
end

app/controllers/page2_controller.rb
class Page2Controller < ApplicationController
  before_action :authenticate_user!

  def index
    @title = 'Page 2'
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  layout "main/layout-blank"
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout "main/layout-blank", only: :new
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super    
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/api/v1/api_helper.rb
module Api::V1::ApiHelper
end

app/helpers/api/v1/profile_helper.rb
module Api::V1::ProfileHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
  def get_token user
    payload = { data: {user: {id: user.id, email: user.email, name: user.name}} }
    payload[:exp] = (Time.now + 100.days).to_i
    JWT.encode payload, Settings.hmac_secret, 'HS256'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agents/_form.slim
= form_for @agent, url: @path, html: {id: "agent_form"} do |f|
  .form-group
    = f.label :name, class: 'form-label'
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :email, class: 'form-label'
    = f.text_field :email, class: 'form-control'

  .form-group
    = f.label :password, class: 'form-label'
    = f.text_field :password, class: 'form-control'

  = f.submit 'Submit', class: 'btn btn-default btn-add-agent'
  |        
  = link_to 'Cancel', agents_path, class: 'btn btn-danger'

app/views/agents/edit.slim
h4.d-flex.justify-content-between.align-items-center
  span.text-muted.font-weight-light Edit Agent  
  
hr.border-light.container-m--x.mt-0.mb-4/

- if @agent.errors.any?
  .alert.alert-danger
    h3
      = pluralize(@agent.errors.count, "error")
      |  prohibited this meeting from being saved:
 
    ul
      - @agent.errors.full_messages.each do |msg|
        li = msg

.card.mb-4
  .card-body
    = render 'form'

app/views/agents/index.slim
- content_for :styles do
  = stylesheet_link_tag 'bootstrap-sweetalert/bootstrap-sweetalert.css', media: 'all'
  = stylesheet_link_tag 'datatables/datatables.css', media: 'all'

- content_for :scripts do  
  = javascript_include_tag 'bootstrap-sweetalert/bootstrap-sweetalert.js'


h4.d-flex.justify-content-between.align-items-center
  span.text-muted.font-weight-light Agents
  = link_to new_agent_path, class: 'btn btn-primary rounded-pill d-block' do
    span.ion.ion-md-add
    | &nbsp; Add Agent
  
hr.border-light.container-m--x.mt-0.mb-4/
- flash.each do |key, value|
  = content_tag :div, value, class: "alert alert-info"

.card  
  - if @agents.any?
    .card-datatable.table-responsive
      #DataTables_Table_1_wrapper.dataTables_wrapper.dt-bootstrap4.no-footer      
        .row
          .col-sm-12
            table#DataTables_Table_1.datatables-demo.table.table-striped.table-bordered.dataTable.no-footer aria-describedby="DataTables_Table_1_info" role="grid" 
              thead
                tr role="row" 
                  th ID
                  th Name
                  th Email                  
                  th Actions
              tbody
                - @agents.each_with_index do |agent, index|
                  tr
                    td=agent.id
                    td=agent.name
                    td=agent.email
                    td
                      = link_to edit_agent_path(agent), class: 'lnr-icon-md', title: 'Edit Agent' do
                        i.lnr.lnr-pencil
                      / |   &nbsp;
                      / = link_to "JavaScript:void(0);", class: 'lnr-icon-md error lnk-trash', data: { id: agent.id},  title: 'Delete Agent' do
                      /   i.lnr.lnr-trash

        .row
          .col-sm-12.col-md-5            
          .col-sm-12.col-md-7
            #DataTables_Table_1_paginate.dataTables_paginate.paging_simple_numbers
              = paginate @agents
  
  
  - else
    p.no-record No agent found.

app/views/agents/new.slim
h4.d-flex.justify-content-between.align-items-center
  span.text-muted.font-weight-light Add Agent  
  
hr.border-light.container-m--x.mt-0.mb-4/

- if @agent.errors.any?
  .alert.alert-danger
    h3
      = pluralize(@agent.errors.count, "error")
      |  prohibited this meeting from being saved:
 
    ul
      - @agent.errors.full_messages.each do |msg|
        li = msg

.card.mb-4
  .card-body
    = form_for @agent, url: '/agents', html: {id: "agent_form"} do |f|
      .form-group
        = f.label :name, class: 'form-label'
        = f.text_field :name, class: 'form-control'

      .form-group
        = f.label :email, class: 'form-label'
        = f.text_field :email, class: 'form-control'

      .form-group
        = f.label :password, class: 'form-label'
        = f.text_field :password, class: 'form-control'

      = f.submit 'Submit', class: 'btn btn-default btn-add-agent'
      |        
      = link_to 'Cancel', agents_path, class: 'btn btn-danger'